version: '3.9'

services:
  app:
    container_name: ticket_system
    build: .
    image: node
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${POSTGRES_TZ}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ticket_system_db?schema=public
    depends_on:
      - db

  db:
    container_name: ticket_system_db
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${POSTGRES_TZ}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
